server:
  port: 9024

spring:
  application:
    name: ticketMixbi

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
      value-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
      properties:
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081

  cloud:
    function:
      definition: process
    stream:
      bindings:
        process-in-0:
          destination: user-in-ticket
        process-in-1:
          destination: products-in-ticket
        process-out-0:
          destination: ticket

      kafka:
        streams:
          bindings:
            process-in-0:
              consumer:
                applicationId: mixbi
                keySerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            process-in-1:
              consumer:
                applicationId: mixbi
                keySerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            process-out-0:
              producer:
                keySerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

          binder:
            brokers: "localhost:9092"
            configuration:
              topology.optimization: all
              state.dir: /tmpdc
              commit.interval.ms: 100
              session.timeout.ms: 10000
              max-poll-interval-ms: 60000
              schema.registry.url: http://localhost:8081
              statestore.cache.max.bytes: 200
              auto.register.schemas: true
              default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

  kafka.producer.properties:
    key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
    value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
    schema.registry.url: http://localhost:8081

  config:
    activate:
      on-profile: default
