server:
  port: 9064

spring:
  application:
    name: ticketRecord

  datasource:
    url: jdbc:postgresql://localhost:5333/postgresBills
    username: Billberus
    password: postgres123B
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  cloud:
    function:
      definition: process
    stream:
      bindings:
        process-in-0:
          destination: ticket

      kafka:
        binder:
          brokers: "localhost:9092"
          configuration:
            commit.interval.ms: 100
            session.timeout.ms: 10000
            max-poll-interval-ms: 60000
            auto.register.schemas: true
            default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        streams:
          bindings:
            process-in-0:
              consumer:
                keySerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

  config:
    activate:
      on-profile: default
