server:
  port: 9064

spring:
  application:
    name: ticketRecord
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ticket-record
      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
      value-deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
      properties:
        specific.avro.reade: true
        schema.registry.url: http://localhost:8081
  datasource:
    url: jdbc:postgresql://localhost:5333/postgresBills
    username: Billberus
    password: postgres123B
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  config:
    activate:
      on-profile: default
