server:
  port: 9004
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: menu
  datasource:
    url: jdbc:postgresql://localhost:5332/postgresProducts
    username: Productberus
    password: postgres123P
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: crud-product-consumer
      auto-offset-reset: earliest
      properties:
        key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: http://localhost:8081

    producer:
      properties:
        key-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        schema.registry.url: http://localhost:8081
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher