version: '1'
services:
  products_db:
    container_name: products
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_PRODUCTS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PRODUCTS}
      PGDATA: /data/postgres
    volumes:
      - db:/data/products
    ports:
      - "5332:5432"

  bills_db:
    container_name: bills
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_BILLS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BILLS}
      PGDATA: /data/bills
    volumes:
      - db:/data/bills
    ports:
      - "5333:5432"

  users_db:
    container_name: user
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_USERS}
      PGDATA: /data/users
    volumes:
      - db:/data/user
    ports:
      - "5334:5432"


