server:
  port: 9014
spring:
  application:
    name: admin
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
      value-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
      properties:
        specific.avro.reade: true
        schema.registry.url: http://localhost:8081
  config:
    activate:
      on-profile: default

KEYPASS: KafkaGang