server:
  port: 9014
spring:
  application:
    name: admin
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        schema.registry.url: http://localhost:8081
  config:
    activate:
      on-profile: default

KEYPASS: KafkaGang