server:
  port: 9014
spring:
  application:
    name: admin
  kafka:
    producer:
      properties:
        key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        schema.registry.url: http://localhost:8081
  config:
    activate:
      on-profile: default

KEYPASS: KafkaGang