server:
  port: 9014
spring:
  application:
    name: admin
  kafka:
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  profiles:
    active: native


KEYPASS: KafkaGang